CREATE TABLE horses (
horse_name VARCHAR(500),
race_ID VARCHAR(500) ,
form VARCHAR(500) ,
horse_weight VARCHAR(500) ,
days_since_last_run VARCHAR(500) ,
horse_age INTEGER ,
horse_nationality VARCHAR(500),
horse_head_gear VARCHAR(500),
horse_notables VARCHAR(500),
jockey_name VARCHAR(500) ,
jockey_form VARCHAR(500) ,
jockey_claim VARCHAR(500),
trainer_name VARCHAR(500) ,
stall INTEGER ,
result VARCHAR(500),
horse_analysis_text VARCHAR(500) ,
horse_added_timestamp TIMESTAMP)